services:

 mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  
      
 user-api:
     build: ./call-booking-application/user-api
     ports:
       - 1004:1004
     environment:
      - MONGO_URL=mongodb://mongoadmin:secret@mongodb:27017/admin?retryWrites=true
     depends_on:
      - mongodb
     user: "userapi"
     networks:
      - app-network

 admin-api:
    build: ./call-booking-application/admin-api
    ports:
      - 1005:1004
    environment:
      - MONGO_URL=mongodb://mongoadmin:secret@mongodb:27017/admin?retryWrites=true
    depends_on:
      - mongodb
    user: "adminapi"
    networks:
      - app-network

 user-ui:
    build: ./call-booking-application/user-ui
    ports:
      - 3000:3000
    depends_on:
      - user-api
    user: "userui"
    networks:
      - app-network
      
 admin-ui:
    build: ./call-booking-application/admin-ui
    ports:
      - 30001:30001
    depends_on:
      - admin-api
    user: "adminui"
    networks:
      - app-network  

volumes:
    mongo-data:

networks:
  app-network:
    driver: bridge    

      
