services:

 mongo_db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=my_db
    volumes:
      - mongo-data:/data/db
      
    

 user-api:
     build: ./call-booking-application/user-api
     ports:
       - 1004:1004
     environment:
      - MONGO_URL=mongodb://mongoadmin:secret@my_db:27017/?retryWrites=true&w=majority
     depends_on:
      - mongo_db

 admin-api:
    build: ./call-booking-application/admin-api
    ports:
      - 1005:1005
    environment:
      - MONGO_URL=mongodb://mongoadmin:secret@my_db:27017/?retryWrites=true&w=majority
    depends_on:
      - mongo_db

 user-ui:
    build: ./call-booking-application/user-ui
    ports:
      - 3000:3000
    depends_on:
      - user-api
      
 admin-ui:
    build: ./call-booking-application/admin-ui
    ports:
      - 30001:30001
    depends_on:
      - admin-api

volumes:
    mongo-data:

      
