apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
  labels: 
    app: admin-ui
  namespace: admin  
spec:
  selector:
    matchLabels:
      app: admin-ui
      role: admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin-ui
        role: admin
    spec:
      volumes:
      - name : admin-ui-v1
        configMap: 
          name: admin-ui-config
      containers:
      - name: admin-ui
        image: varshithakj/full_stack_application_admin-ui:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        resources:
            requests:
              memory: "250Mi"
              cpu: "1Gi"
            limits:
              memory: "500Mi"
              cpu: "2Gi"
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 3 
        volumeMounts:
          - name: admin-ui-v1
            mountPath: /app/.env
            subPath: .env

