apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  namespace: admin
spec:
  type: NodePort
  selector:
    app: admin-ui
    role: admin
  ports:
  - port: 1025 #service port
    targetPort: 1025
    nodePort: 30001