apiVersion: v1
kind: Secret
metadata:
  name: admin-api-secrets
  namespace: admin
type: Opaque
data:
  connectingstring: IG1vbmdvZGI6Ly9tb25nb2FkbWluOnNlY3JldEBtb25nby1kYi1zdmMuZGF0YWJhc2Uuc3ZjLmNsdXN0ZXIubG9jYWwvYWRtaW4/cmV0cnlXcml0ZXM9dHJ1ZQ==
  
