apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: database
spec:
  selector:
    app: mongo-db 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: db-ports
  type: ClusterIP
