apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongo-db
  serviceName: mongo-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      nodeSelector: 
          role: mongo-db
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
              name: db-ports
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:  
                  name: mongo-db-secrets
                  key: dbuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mongo-db-secrets
                  key: dbpass
          resources: 
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 8Gi
              cpu: 1500m
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 3
          livenessProbe:
            exec:
              command:
                - "mongosh"
                - '--eval'
                - "db.adminCommand('ping')"
            initialDelaySeconds: 3
            timeoutSeconds: 3
            periodSeconds: 3
