apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  namespace: user
spec:
  type: NodePort
  selector:
    app: user-api
    role: user
  ports:
  - port: 1025 #service port
    targetPort: 1025
    nodePort: 32001
